### ISSUE TITLE
app crashed when delete all env tab

### ISSUE THREAD

**Issue by b1tg** [mardiros/rustaman#8]
# Description
when i delete all the environment tabs, app crashed and can not open any more.

program  crashed when TogglingEnvironmentIndex(0) but "id"=0 don't exist in `workspace.json`

https://github.com/mardiros/rustaman/blob/db56811eca2485883e0e79143000e40dc784395a/src/ui/environ_editor.rs#L234-L242

# Error Message
```
 INFO  rustaman::ui::window          > Deleting environment 1
 INFO  rustaman::models::workspace   > Writing workspace in file /Users/ch/Library/Preferences/rustaman/workspace.json
 INFO  rustaman::ui::environ_editor  > Switch to page 0
thread 'main' panicked at 'Should be a valid tab page index', src/libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:95
   8: core::char::methods::<impl char>::escape_debug
             at src/libcore/option.rs:1008
   9: <core::option::Option<T>>::expect
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libcore/option.rs:322
  10: <rustaman::ui::environ_editor::EnvironEditor as relm_state::Update>::update
             at src/ui/environ_editor.rs:237
  11: relm_state::update_component
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-state-0.15.0/src/lib.rs:167
  12: relm_state::init_component::{{closure}}
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-state-0.15.0/src/lib.rs:150
  13: <relm_core::SourceData<MSG> as relm_core::source::SourceFuncs>::dispatch
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-core-0.15.0/src/lib.rs:146
  14: relm_core::source::dispatch
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-core-0.15.0/src/source.rs:73
  15: g_main_context_dispatch
  16: g_main_context_iterate
  17: g_main_loop_run
  18: gtk_main
  19: <core::str::CharIndices<'a> as core::iter::iterator::Iterator>::next
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/gtk-0.5.0/src/auto/functions.rs:273
  20: relm::run
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/lib.rs:383
  21: relm::widget::Widget::run
             at /Users/ch/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/relm-0.15.0/src/widget.rs:63
  22: rustaman::main
             at src/main.rs:40
  23: std::rt::lang_start::{{closure}}
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libstd/rt.rs:74
  24: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  25: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  26: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  27: std::rt::lang_start
             at /rustc/0c999ed132d67bf2520643e9bd619972cf3888ba/src/libstd/rt.rs:74
  28: rustaman::main

```
# env
mac osx 10.12.6
rustc 1.32.0-nightly (0c999ed13 2018-12-03)

**Comment by b1tg** [comment]
i want to contribute to this project, any suggestion?

**Comment by mardiros** [comment]
To fix this issue, the last tag page must not be close, so when there is only one environment, the close button should be hidden.

When there is 2 environments, both have the close button displayed.

And, it could be awesome to have a confirmation box when closing an environment.

I already close two times an environment by mistake and it could be great...

The number of environments is the length of the EnvironEditor.environments vector from the 
environ_editor module.

a reference to the close image must be kept in the environ_sources which is currently

```
    environ_sources: HashMap<u32, (usize, String, ScrolledWindow, SourceView)>,
```
in order to `.show()` `.hide()` it.


If you have questions, let me now.

**Comment by b1tg** [comment]
Hi mardiros, sorry for that long time waiting.
i was trying to fix this bug and i found two more bugs related to env-tabs:
## Bugs
1.  at any time i delete the current env tab, app crashed...
2. this one is more complicated, below is bug reproduction process:
 (1) at start i have two active env (t1 and t2) in my workspace.json, start the app
 (2) switch to t2 as current tab
 (3) delete t1
 (4) create new env (t3)
 (5) switch to t3 as current tab
 (6) delete t2, app crash here....
## Analysis
Bug#1: when i delete current tab, app want to do `Msg::TogglingEnvironmentIndex(id)`, but the id it got was just deleted , i could't figure out why app switch to that `id`.
https://github.com/mardiros/rustaman/blob/db56811eca2485883e0e79143000e40dc784395a/src/ui/environ_editor.rs#L326-L331

Bug#2: 
in step(4) when i create t3, the index `append_page()` returned was in used, so old value in environ_sources then be covered, so when i deleted t2, app crash, i am confused about how index was generated.
https://github.com/mardiros/rustaman/blob/db56811eca2485883e0e79143000e40dc784395a/src/ui/environ_editor.rs#L216-L219



i did  some hack  fix, but it may have something unwanted
https://github.com/b1tg/rustaman/tree/issue/env-deleting

**Comment by mardiros** [comment]
Hi @b1tg 

I guess it should be a (MessageDialog)[https://gtk-rs.org/docs/gtk/struct.MessageDialog.html] not a gtk::Window.

It should works like example here:

https://github.com/antoyo/relm/blob/master/examples/async/src/main.rs#L121

**Comment by mardiros** [comment]
For the crash when the active tab is selected, here is the fix:

https://github.com/mardiros/rustaman/pull/9

**Comment by b1tg** [comment]
@mardiros 
here is the pull request #10

**Comment by mardiros** [comment]
I've merge your branch in https://github.com/mardiros/rustaman/pull/9 and it does not crash.

A bug remains after but there is no crash:

 - Add a tab A
 - Add a tab B
 - Add a tab C
 - Delete the tab B

Then the tab A is selected, but we can't select tab C

I prefer to fix it in another branch; I am OK to merge ALL opened MR right now.
And fix the remaining bug can be fixed later in another branch. WDYT ?

It is a really good improvement ! Thanks !

**Comment by b1tg** [comment]
@mardiros 
I think i found out why this bug happens, `environ_sources` is a Hashmap which use index as key, however, the gtk.notebook treat env tabs as a Array.
After you add three tabs, hashmap looks like` {"0": "A", "1": "B", "2": "C"}`, then delete tab B, it became `{"0": "A", "2": "C"}`, now you want select tab C,  notebook treat C as the second tab but it can't found key "1" in Hashmap, app crash. 

As i test, there are some other bugs caused by this.

I did a commit to fix this, you can check it out.
https://github.com/mardiros/rustaman/pull/10/commits/13f976b60a264c9849b0f2b43154f1bb258cd53a
this commit related to some code of "confirm delete", so i didn't create a new branch, if it not what you want, tell me what to do.

**Comment by mardiros** [comment]
:open_mouth: I actually wright a vector at first, but did not find a proper solution actually.

Awesome!

**Comment by mardiros** [comment]
Fixed by https://github.com/mardiros/rustaman/pull/10
